### ISSUE TITLE
Add Discord status for Minecraft server online status and player count

### ISSUE THREAD

**Issue by lucas2kdk** [theflyingbirdsmc/TFB-Network#147]
### Description: 

- [x] Currently, we don't have a way to show if our Minecraft server is online or how many players are currently on. This task is to add a 
- [x]  Discord status that will display whether the server is online and how many players are currently playing.

### Acceptance Criteria:

- [x] Discord status updates automatically based on the Minecraft server's status
- [x] Discord status displays the server's online/offline status
- [x] Discord status displays the number of players currently on the server
- [x] Code changes are tested and documented

### Tasks:

- [x] Research how to query Minecraft server status using an API or plugin
- [x] Implement a script that queries the server status and player count
- [x] Integrate the script with the Discord API to update the status
- [x] Test the functionality of the Discord status update and player count display
- [x] Document the code changes and update the README.md file with instructions on how to use the feature.

**Comment by Fuglen** [comment]
I bumped into this ;)
https://github.com/PetyXbron/minecraft-bot

**Comment by Fuglen** [comment]
And then I joined our current bot's Discord support server and decided we should probably give this guy some more time
![image](https://user-images.githubusercontent.com/6181362/234068076-01350cb8-9ecc-4ea3-ae93-579627338601.png)
