### ISSUE TITLE
Implement a development environment for TFB

### ISSUE THREAD

**Issue by Fuglen** [theflyingbirdsmc/TFB-Network#3]
**As a** server manager/admin
**I want** to update plugins easier, test everything in a safe environment and keep track of changes in Git,
**so that** players can play on TFB without getting affected by our work.

Make a SSOT repo with deployment scripts to make a folder that will be pushed Live (if all tests passes?). The admin does not push to Live server and we can have a shared repo where we can update ALL plugins on ALL servers at once with pluGET. Tricky part is to make dev-env configurations so it works locally and transform all the files ready to deploy so that it "just works" on Live.

The dev-env will contain all servers at once where it's easier to start, switch, and transfer files between them. This also solves the problem with editing multiple files for all our servers at once. If we want to update some part of our tablist in TAB, we can do so in VSCode as described https://stackoverflow.com/questions/37346481/how-do-i-find-and-replace-all-occurrences-in-all-files-in-visual-studio-code - This is only possible if we convert TFB to have only 1 Github repository and I do some tinkering with the dev environment.

Another thing is to have a Github pipeline with local workers to test if the servers that are edited is working as intented and passes some tests and after that it can automatically deploy/continous deliver the changes to Live over SFTP.
THANK YOU Torben Worm (DevOps teacher) for your input, much appreciated!

We need a script to convert Dev configs (IP to database and IP's to servers in FlameCord etc.) and change them to what Live uses. It would also be cool to make a pipeline so that everyone can contribute. The pipeline would need premium plugins which we have to make sure never gets in the hands of non-staff by using SFTP secrets on Github in the pipeline. That way, everyone can commit/push and get their features tested and delivered into the real server.

**SUBTASKS:**
- [x] Transform TFB servers into a single repo (SSOT) (Adding all of the servers)
- [x] Install pluGET and FlameCord from Github
- [ ] Make Github Actions (Pipeline) to test a server starts with no issues and all plugins are working
- [x] The Pipeline should be able to push to Live with SFTP secrets (Continous Delivery)
- [x] Make Github Secrets for SFTP to Live, maybe use TFB account?
- [x] #13
- [x] Make anyone able to make a PR to a branch, true power of open-source!
- [x] #79
- [ ] #80

**Comment by Fuglen** [comment]
Make a SSOT repo with deployment scripts to make a folder that will be pushed Live (if all tests passes?). The admin does not push to Live server and we can have a shared repo where we can update ALL plugins on ALL servers at once with pluGET. Tricky part is to make dev-env configurations so it works locally and transform all the files ready to deploy so that it "just works" on Live. 

The dev-env will contain all servers at once where it's easier to start, switch, and transfer files between them. This also solves the problem with editing multiple files for all our servers at once. If we want to update some part of our tablist in TAB, we can do so in VSCode as described https://stackoverflow.com/questions/37346481/how-do-i-find-and-replace-all-occurrences-in-all-files-in-visual-studio-code - This is only possible if we convert TFB to have only 1 Github repository and I do some tinkering with the dev environment.

Another thing is to have a Github pipeline with local workers to test if the servers that are edited is working as intented and passes some tests and after that it can automatically deploy/continous deliver the changes to Live over SFTP.
THANK YOU Torben Worm (DevOps teacher) for your input, much appreciated!

**Comment by Fuglen** [comment]
We need a script to convert Dev configs (IP to database and IP's to servers in FlameCord etc.) and change them to what Live uses. It would also be cool to make a pipeline so that everyone can contribute. The pipeline would need premium plugins which we have to make sure never gets in the hands of non-staff by using SFTP secrets on Github in the pipeline. That way, everyone can commit/push and get their features tested and delivered into the real server.

**Comment by Fuglen** [comment]
Closing this old one, still not solved but good for now
